
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

logging:
  level:
    root: info

stat-tracker:
  discord-interface:
    url: "http://${DISCORD_INTERFACE_HOST}:${DISCORD_INTERFACE_PORT}"
