name: build docker-dev-images

on:
  workflow_call:
    inputs:
      version-number:
        required: true
        type: string
      version-number-major:
        required: true
        type: string
      version-number-minor:
        required: true
        type: string
      version-number-patch:
        required: true
        type: string
      discord-interface-container-name:
        required: true
        type: string
      spring-backend-container-name:
        required: true
        type: string


jobs:
  build-spring-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_token }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./progamer-bot-spring-be
          file: ./progamer-bot-docker/progamer-bot-spring-backend.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/meepmr/${{ inputs.spring-backend-container-name }}:latest
            ghcr.io/meepmr/${{ inputs.spring-backend-container-name }}:${{ inputs.version-number }}
            ghcr.io/meepmr/${{ inputs.spring-backend-container-name }}:${{ inputs.version-number-major }}
            ghcr.io/meepmr/${{ inputs.spring-backend-container-name }}:${{ inputs.version-number-major }}.${{ inputs.version-number-minor }}

  build-discord-interface-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{ inputs.version-number }}
        working-directory: ./discord-js-interface
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_token }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./discord-js-interface
          file: ./progamer-bot-docker/discord-js-interface.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/meepmr/${{ inputs.discord-interface-container-name }}:latest
            ghcr.io/meepmr/${{ inputs.discord-interface-container-name }}:${{ inputs.version-number }}
            ghcr.io/meepmr/${{ inputs.discord-interface-container-name }}:${{ inputs.version-number-major }}
            ghcr.io/meepmr/${{ inputs.discord-interface-container-name }}:${{ inputs.version-number-major }}.${{ inputs.version-number-minor }}
