name: build docker-dev-images

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  get-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.get_version_number.outputs.version_no }}
    steps:
      - id: get_version_number
        run: echo "version_no=$(date +'%y.%m').${{ github.run_number }}" >> $GITHUB_OUTPUT

  build-spring-backend-image-dev:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_token }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./progamer-bot-spring-be
          file: ./progamer-bot-docker/progamer-bot-spring-backend.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/meepmr/progamer-bot-spring-be-dev:latest
            ghcr.io/meepmr/progamer-bot-spring-be-dev:${{needs.get-version-number.outputs.version-no}}

  build-discord-interface-image-dev:
    runs-on: ubuntu-latest
    needs: get-version-number
    steps:
      - uses: actions/checkout@v3
      - name: Update version number in package.json
        run: npm version ${{needs.get-version-number.outputs.version-no}}
        working-directory: ./discord-js-interface
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Authenticate To ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_token }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./discord-js-interface
          file: ./progamer-bot-docker/discord-js-interface.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/meepmr/discord-interface-dev:latest
            ghcr.io/meepmr/discord-interface-dev:${{needs.get-version-number.outputs.version-no}}
