name: Deploy Prod

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  get-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.get_version_number.outputs.version_no }}
      version-no-major: ${{ steps.get_version_number.outputs.version_no }}
      version-no-minor: ${{ steps.get_version_number.outputs.version_no }}
      version-no-patch: ${{ steps.get_version_number.outputs.version_no }}
    steps:
      - id: get_version_number
        run: echo "version_no=$(cut -c2- <<< ${{ github.ref_name }})" >> $GITHUB_OUTPUT
      - id: get_major_version_number
        run: echo "version_no=$(cut -d '.' -f 1 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT
      - id: get_minor_version_number
        run: echo "version_no=$(cut -d '.' -f 2 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT
      - id: get_patch_version_number
        run: echo "version_no=$(cut -d '.' -f 3 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT

  build-prod-images:
    needs: get-version-number
    uses: ./.github/workflows/build-docker-images.yml
    with:
      version-number: ${{ needs.get-version-number.outputs.version-no }}
      version-number-major: ${{ needs.get-version-number.outputs.version-no-major }}
      version-number-minor: ${{ needs.get-version-number.outputs.version-no-minor }}
      version-number-patch: ${{ needs.get-version-number.outputs.version-no-patch }}
      discord-interface-container-name: 'discord-interface'
      spring-backend-container-name: 'progamer-bot-spring-backend'
    secrets: inherit


  deploy-prod:
    needs: build-prod-images
    uses: ./.github/workflows/execute-deployment.yml
    with:
      environment: 'prod'
    secrets: inherit
