name: Deploy Dev

on:
  push:
    branches:
      - development

jobs:
  get-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-no: ${{ steps.get_version_number.outputs.version_no }}
      version-no-major: ${{ steps.get_major_version_number.outputs.version_no }}
      version-no-minor: ${{ steps.get_minor_version_number.outputs.version_no }}
      version-no-patch: ${{ steps.get_patch_version_number.outputs.version_no }}
    steps:
      - id: get_version_number
        run: echo "version_no=$(date +'%y.%m').${{ github.run_number }}" >> $GITHUB_OUTPUT
      - id: get_major_version_number
        run: echo "version_no=$(cut -d '.' -f 1 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT
      - id: get_minor_version_number
        run: echo "version_no=$(cut -d '.' -f 2 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT
      - id: get_patch_version_number
        run: echo "version_no=$(cut -d '.' -f 3 <<< "${{ steps.get_version_number.outputs.version_no }}")" >> $GITHUB_OUTPUT

  build-dev-images:
    needs: get-version-number
    uses: ./.github/workflows/build-docker-images.yml
    with:
      version-number: ${{ needs.get-version-number.outputs.version_no }}
      version-number-major: ${{ needs.get-version-number.outputs.version_no-major }}
      version-number-minor: ${{ needs.get-version-number.outputs.version_no-minor }}
      version-number-patch: ${{ needs.get-version-number.outputs.version_no-patch }}
      discord-interface-container-name: 'discord-interface-dev'
      spring-backend-container-name: 'progamer-bot-spring-be-dev'
    secrets: inherit

  deploy-dev:
    needs: build-dev-images
    uses: ./.github/workflows/execute-deployment.yml
    with:
      environment: 'dev'
    secrets: inherit
