name: deploy application
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: "Deploy to ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh.key
          chmod 600 ~/.ssh/ssh.key
          cat >>~/.ssh/config <<END
          Host vps
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ssh.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: deploy
        run: ssh vps '${{ vars.DEPLOYMENT_COMMAND }}'
