name: deploy application
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: "Deploy to ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          SSH_USER: op://Hosting-Secrets/OVH-jklein-vps-1/Admin Console/admin-console-username
          SSH_KEY: op://Hosting-Secrets/VPS-GitHub-Access-Key/private key
          SSH_HOST: op://Hosting-Secrets/OVH-jklein-vps-1/Admin Console/admin-console-URL
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh.key
          chmod 600 ~/.ssh/ssh.key
          cat >>~/.ssh/config <<END
          Host vps
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ssh.key
            StrictHostKeyChecking no
          END
      - name: deploy
        run: ssh vps '${{ vars.DEPLOYMENT_COMMAND }}'
