name: Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy-dev:
    uses: ./.github/workflows/execute-deployment.yml
    with:
      environment: 'dev'
    secrets: inherit
