name: Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/development'
    uses: ./.github/workflows/execute-deployment.yml
    with:
      environment: 'dev'
    secrets: inherit

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/execute-deployment.yml
    with:
      environment: 'prod'
    secrets: inherit
